### ISSUE TITLE
Bad performances of messagesource if launched from jar

### ISSUE THREAD

**Issue by Glorfingol** [mgargadennec/blossom#13]
When blossom is launched from jar, blossom pages are really slow.
Maybe something to do with how freemarker looks for templates in the application when it is packaged as jar.
Maybe some cache to install on freemarker templates ?

**Comment by mgargadennec** [comment]
The problem originates from MultiClasspathReloadableBundleMessageSource.

**Comment by mgargadennec** [comment]
We now use PathMatchingResourcePatternResolver during the  ReloadableResourceBundleMessageSource instantiation to fetch the file name in the whole classpath under classpath*:/messages/*.properties.

The result is mapped to an array of "classpath:/message/<filename>" then used in setBasenames() to initialize the ReloadableResourceBundleMessageSource.
