### ISSUE TITLE
Question sur l'implémentation de .equals()

### ISSUE THREAD

**Issue by cardiweb** [mgargadennec/blossom#28]
https://github.com/mgargadennec/blossom/blob/c369fcac6e6a1fbb3d8169597529eabf7b9b77ea/blossom-core/blossom-core-common/src/main/java/fr/mgargadennec/blossom/core/common/dto/AbstractDTO.java#L65

est-ce que 2 objets avec des ids null doivent vraiment être considérés comme égaux ?

**Comment by mgargadennec** [comment]
Nope. Fixed.
