### ISSUE TITLE
MySQL database : Blob type error on blossom_user.avatar

### ISSUE THREAD

**Issue by RLejolivet** [mgargadennec/blossom#34]
When trying to launch a sample project on MySQL, I had the following error:

    org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [avatar] in table [blossom_user]; found [blob (Types#LONGVARBINARY)], but expecting [longblob (Types#BLOB)]

Fixed it by changing the `@Column` statement (fr/mgargadennec/blossom/core/user/User.java:50):

    @Column(name = "avatar", columnDefinition = "BLOB")

But that may break other DB Managers (?)

**Comment by mgargadennec** [comment]
Fixed by setting liquibase field to "longblob"
