### ISSUE TITLE
MySQL Database: Quartz init script

### ISSUE THREAD

**Issue by RLejolivet** [mgargadennec/blossom#35]
The Quartz init script uses H2 SQL style, and fails on MySQL (MariaDB 10.2 in my case) with the following error:

        org.springframework.jdbc.datasource.init.ScriptStatementFailedException: Failed to execute SQL script statement #1 of class path resource [quartz_tables.sql]: CREATE TABLE QRTZ_CALENDARS ( SCHED_NAME VARCHAR(120) NOT NULL, CALENDAR_NAME VARCHAR (200) NOT NULL , CALENDAR IMAGE NOT NULL ); nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'IMAGE NOT NULL )' at line 1

**Comment by mgargadennec** [comment]
We now use Liquibase instead of a `AbstractDatabaseInitializer` to perform Quartz table creation for multiple databases types (h2, hsqldb, mysql, oracle, postgresql)
